
export const blogList = [

  {
    id: 9,
    title: "Discover Paris: A Traveler's Guide",
    category: 'Paris',
    description:"Embark on an enchanting journey to Paris, where adventure awaits around every corner. Dive into the heart of this vibrant destination and uncover its hidden treasures, from majestic landmarks to quaint streets filled with local charm. Whether you're seeking adrenaline-pumping outdoor activities, immersing yourself in rich cultural heritage, or simply indulging in the culinary delights of the region, this comprehensive guide has you covered. With expert insights and insider tips, you'll navigate Paris like a seasoned traveler, unlocking unforgettable experiences along the way. Get ready to create lifelong memories and embark on the ultimate adventure in Paris.",
    authorName: ' John Smith',
    authorAvatar: '/assets/images/instagram-reels-avatar.jpeg',
    createdAt: 'June 15, 2021',
    cover: 'https://www.travelawaits.com/wp-content/uploads/2021/04/a-unique-view-of-the-eiffel-td2985a.jpg',
  },
  {
    id: 10,
    title: "Roaming Through Rome: An Explorer's Handbook",
    category: 'Rome',
     description:
      "Embark on an epic journey through Rome, where ancient history and modern culture collide. Uncover the secrets of the Eternal City as you wander through its iconic landmarks, bustling piazzas, and hidden gems. Whether you're captivated by ancient ruins, enchanted by Renaissance art, or craving authentic Italian cuisine, this guide will lead you to the heart of Rome's vibrant soul. Prepare to be swept away by the charm and beauty of the Eternal City.",
    authorName: 'Dua Fatima',
    authorAvatar: '/assets/images/reel-master-avatar.jpeg',
    createdAt: 'June 20, 2021',
    cover: "https://tourismmedia.italia.it/is/image/mitur/20220127150143-colosseo-roma-lazio-shutterstock-756032350-1?wid=375&hei=500&fit=constrain,1&fmt=webp",
  },
  {
    id: 11,
    title: "Adventures in the Amazon: A Nature Lover's Guide",
    category: 'Travel',
    description:"Explore the untamed wilderness of the Amazon rainforest, where biodiversity thrives and adventure awaits at every turn. Trek through lush jungle trails, navigate winding rivers, and encounter exotic wildlife in their natural habitat. Whether you're an avid birdwatcher, a passionate eco-traveler, or simply seeking a wild escape from civilization, this guide will help you navigate the wonders of the Amazon with ease. Get ready for an unforgettable journey into the heart of the world's largest tropical rainforest.",
    authorName:"Emily Johnson",
    authorAvatar: '/assets/images/tweet-tactician-avatar.png',
    createdAt: 'June 25, 2021',
    cover: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTQEIndt8kaT6XZbUxNqR9zrstInEc_kMl5A&usqp=CAU",
  },
  {
    id: 12,
    title: 'Safari Serenity: A Guide to African Wildlife',
    category: 'Safari',
    description:
      "Embark on a once-in-a-lifetime safari adventure across the vast landscapes of Africa. Witness the majestic beauty of the continent's iconic wildlife, from mighty elephants and graceful giraffes to stealthy predators on the prowl. Whether you're drawn to the sweeping savannas of the Serengeti, the lush wetlands of the Okavango Delta, or the rugged terrain of the Maasai Mara, this guide will lead you on an unforgettable journey through Africa's untamed wilderness.",
    authorName: 'TourVirtuoso',
    authorAvatar: '/assets/images/video-virtuoso-avatar.jpeg',
    createdAt: 'July 01, 2021',
    cover: "https://static.toiimg.com/photo/msid-104997103,width-96,height-65.cms",
  },
  {
    id: 13,
    title: 'Exploring the Enchanting Islands of Greece',
    category: 'Travel Greece',
    description:
      "Set sail for a magical journey through the sun-drenched islands of Greece, where ancient history meets stunning natural beauty. Discover the whitewashed villages of Santorini, the archaeological wonders of Crete, and the hidden coves of Mykonos. Whether you're seeking relaxation on pristine beaches, adventure in rugged landscapes, or a taste of Greek mythology, this guide will help you navigate the wonders of the Greek islands with ease.",
    authorName: 'GreeceInsider',
    authorAvatar: '/assets/images/fb-insider-avatar.jpeg',
    createdAt: 'July 05, 2021',
    cover: "https://a.cdn-hotels.com/gdcs/production150/d1979/7f6b3cf0-f585-11e8-a5a3-0242ac110006.jpg?impolicy=fcrop&w=1600&h=1066&q=medium",
  },
  {
    id: 14,
    title:"Mystical Wonders of Machu Picchu: A Journey to the Lost City",
    category:'Architecture & History',
    description:
      " Venture into the heart of the Andes Mountains and uncover the mysteries of Machu Picchu, the legendary Lost City of the Incas. Trek along ancient Inca trails, marvel at breathtaking mountain vistas, and explore the awe-inspiring ruins of this UNESCO World Heritage Site. Whether you're an intrepid hiker, a history enthusiast, or simply in search of spiritual enlightenment, this guide will lead you on an unforgettable journey to one of the world's most iconic archaeological wonders.",
    authorName: 'HistoryMaestro',
    authorAvatar: '/assets/images/linkedin-maestro-avatar.jpeg',
    createdAt: 'July 10, 2021',
    cover: "https://i.natgeofe.com/n/5bcb3613-ba9c-451f-a4d7-58201fd27b53/01-machu-picchu-secrets_3x2.jpg?w=718&h=479",
  },
  {
    id: 15,
    title: "Island Paradise: Discovering the Beauty of Bali",
  category: 'Beach Life',
  description: "Escape to the tropical paradise of Bali, where lush rainforests, pristine beaches, and vibrant culture await. Immerse yourself in the spiritual tranquility of Ubud, surf the legendary waves of Kuta, or party till dawn in Seminyak. Whether you're seeking relaxation, adventure, or cultural immersion, this guide will help you uncover the best of Bali's hidden gems and unforgettable experiences.",
  authorName: 'SnapchatSavvy',
    authorAvatar: '/assets/images/snapchat-savvy-avatar.png',
    createdAt: 'July 15, 2021',
    cover:"https://balidave.com/wp-content/uploads/2022/11/best-hotel-bali.jpeg",
  },
  {
    id: 16,
    title:  "Marvels of Marrakech: A Journey Through Moroccan Heritage",
    category: 'City Guide',
    description:
      "Embark on a sensory adventure through the ancient streets and vibrant souks of Marrakech, where history, culture, and tradition converge. Lose yourself in the labyrinthine alleys of the medina, explore the opulent palaces of the past, and savor the tantalizing flavors of Moroccan cuisine. Whether you're captivated by the allure of the Sahara Desert, enchanted by the colors of the Atlas Mountains, or simply seeking a taste of exotic charm, this guide will lead you to the heart of Moroccan heritage.",
    authorName: 'TikTokTrailblazer',
    authorAvatar: '/assets/images/tiktok-trailblazer-avatar.jpeg',
    createdAt: 'July 20, 2021',
    cover: 'https://media.gq-magazine.co.uk/photos/5d138f50976fa31476f39436/master/pass/marrakech-gq-9oct18_istock_b.jpg',
  },
  {
    id: 17,
    title: "Sailing the Croatian Coast: A Guide to Adriatic Adventure",
    category: 'Boating & Cruising',
    description:
      "Set sail on a journey of discovery along the picturesque coastline of Croatia, where crystal-clear waters, ancient ruins, and charming seaside villages await. Explore the historic city walls of Dubrovnik, island-hop through the idyllic Dalmatian archipelago, and swim in secluded coves surrounded by pristine nature. Whether you're a seasoned sailor, a history buff, or simply in search of sun-drenched shores, this guide will help you navigate the Adriatic's hidden treasures with ease.",
    authorName: 'SeaExplorer',
    authorAvatar: '/assets/images/igtv-innovator-avatar.png',
    createdAt: 'July 25, 2021',
    cover: "https://s3.eu-west-1.amazonaws.com/tripsmiths.assets.d3r.com/images/hero-tall_laptop/549763-97175-shutterstock-764972821.jpg",
  },
  {
    id: 18,
    title: "Tokyo Tales: A Cultural Odyssey Through Japan's Capital",
    category: "Culture & Tradition",
    description:
      "Immerse yourself in the vibrant energy and rich cultural tapestry of Tokyo, Japan's bustling metropolis where tradition meets innovation. Wander through the neon-lit streets of Shinjuku, experience the tranquility of traditional tea ceremonies in Asakusa, and indulge in culinary delights at the city's world-renowned restaurants. Whether you're captivated by ancient temples, fascinated by cutting-edge technology, or simply seeking a taste of urban adventure, this guide will lead you on a journey through Tokyo's diverse neighborhoods and iconic landmarks.",
    authorName: "Tokyo Twitcher",
    authorAvatar: 'https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png',
    createdAt: 'July 30, 2021',
    cover:"https://www.gotokyo.org/en/plan/tokyo-outline/images/main.jpg",
  },
];
